version: 40
jobs:
- name: backend-rust-ci
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: rust-ci
    runInContainer: true
    image: rust:1.85-bookworm
    interpreter: !DefaultInterpreter
      commands: |
        set -eux
        rustup component add rustfmt clippy
        cargo fmt --all
        cargo clippy --workspace --all-targets
        cargo check --locked -p hypertide-server --bin hypertide
        cargo check --locked -p hypertide-cli --bin ht
        cargo test --workspace --all-targets
        cargo build --workspace --release
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 7200
